### ISSUE TITLE
Asset Types and Attribute Types end-points fail

### ISSUE THREAD

**Issue by pral2a** [OrganicityEu/organicity-discovery-api#6]
The types endpoints as defined here fail:

https://organicityeu.github.io/api/AssetDiscovery.html#operation--assets-types--types--get

Check on:
http://discovery.organicity.eu/v0/assets/types *Returns 404*
http://discovery.organicity.eu/v0/assets/attributes/types  *Returns 404*
http://discovery.organicity.eu/v0/assets/types/urn:oc:entitytype:iot  *Returns 404*

**Comment by hiromipaw** [comment]
This is because the documentation had to be updated.

The endpoint is:
http://discovery.organicity.eu/v0/types
Simply because types aren't defined just for assets, but for object in organicity.
Attributes endpoint wasn't defined because there were no attributes as per 2/3 weeks ago.

For single types endpoint as:
http://discovery.organicity.eu/v0/types/urn:oc:entitytype:districtprofile
Check what the api returns (not discovery api). It is very probable that still returns []. Therefore discovery returns a Not Found error.

**Comment by pral2a** [comment]
Thanks for the quick reply. Haven't look at the source and thought you cross checked the swagger.

This works fine:

http://discovery.organicity.eu/v0/types/
http://discovery.organicity.eu/v0/types/iotdevice

What's the proper path for `/assets/attributes/types` si I can add it on the documentation?

**Comment by hiromipaw** [comment]
There is no path for attributes types because we defined only types. Any type can be queried from the types endpoint.

**Comment by pral2a** [comment]
Ok, so next time please check the API documentation when I ask you to do so. It makes one feels stupid:

https://organicityeu.github.io/api/AssetDiscovery.html#operation--assets-attributes-types--types--get

**Comment by hiromipaw** [comment]
Check you slack messages. I have told you this same thing 3 weeks ago. Thanks.

**Comment by pral2a** [comment]
Ok documentation updated:

https://organicityeu.github.io/api/AssetDiscovery.html
