### ISSUE TITLE
Access Scope

### ISSUE THREAD

**Issue by pral2a** [OrganicityEu/organicity-discovery-api#7]
Check `access:scope` implementation against the AAA service

**Example:**

http://discovery.organicity.eu/v0/assets/urn:oc:entity:experimenters:86d7edce-5092-44c0-bed8-da4beaa3fbc6:58171db0aeb046575877ad5b:asset8257823

The access:scope of the Asset is private, but it is accessable via the public ADS

**Comment by hiromipaw** [comment]
If the assets are accessed through orion the proxy takes care of this. For all the endpoints that go through mongo, nothing regarding public/private assets was implemented. The reason is that there were no private assets at the time I left development on the API. This is a new feature unfortunately.

**Comment by pral2a** [comment]
Yes I know @hiromipaw This are just issue I open for a PR I'm working
